//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2LinkXamarin.WebServiceClients
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageModel", Namespace="http://schemas.datacontract.org/2004/07/M2Link.WebServiceModels")]
    public partial class MessageModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContentField;
        
        private System.Guid MessageIdField;
        
        private string UserField;
        
        private System.Guid UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="M2LinkXamarin.WebServiceClients.IWSMessage")]
    public interface IWSMessage
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/DoWork", ReplyAction="http://tempuri.org/IWSMessage/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSMessage/DoWork", ReplyAction="http://tempuri.org/IWSMessage/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/GetMessages", ReplyAction="http://tempuri.org/IWSMessage/GetMessagesResponse")]
        M2LinkXamarin.WebServiceClients.MessageModel[] GetMessages(System.Guid user);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSMessage/GetMessages", ReplyAction="http://tempuri.org/IWSMessage/GetMessagesResponse")]
        System.IAsyncResult BeginGetMessages(System.Guid user, System.AsyncCallback callback, object asyncState);
        
        M2LinkXamarin.WebServiceClients.MessageModel[] EndGetMessages(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMessage/CreateMessage", ReplyAction="http://tempuri.org/IWSMessage/CreateMessageResponse")]
        M2LinkXamarin.WebServiceClients.MessageModel CreateMessage(System.Guid user, string messageContent);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSMessage/CreateMessage", ReplyAction="http://tempuri.org/IWSMessage/CreateMessageResponse")]
        System.IAsyncResult BeginCreateMessage(System.Guid user, string messageContent, System.AsyncCallback callback, object asyncState);
        
        M2LinkXamarin.WebServiceClients.MessageModel EndCreateMessage(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSMessageChannel : M2LinkXamarin.WebServiceClients.IWSMessage, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMessageClient : System.ServiceModel.ClientBase<M2LinkXamarin.WebServiceClients.IWSMessage>, M2LinkXamarin.WebServiceClients.IWSMessage
    {
        
        public WSMessageClient()
        {
        }
        
        public WSMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WSMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void DoWork()
        {
            base.Channel.DoWork();
        }
        
        public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        public void EndDoWork(System.IAsyncResult result)
        {
            base.Channel.EndDoWork(result);
        }
        
        public M2LinkXamarin.WebServiceClients.MessageModel[] GetMessages(System.Guid user)
        {
            return base.Channel.GetMessages(user);
        }
        
        public System.IAsyncResult BeginGetMessages(System.Guid user, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetMessages(user, callback, asyncState);
        }
        
        public M2LinkXamarin.WebServiceClients.MessageModel[] EndGetMessages(System.IAsyncResult result)
        {
            return base.Channel.EndGetMessages(result);
        }
        
        public M2LinkXamarin.WebServiceClients.MessageModel CreateMessage(System.Guid user, string messageContent)
        {
            return base.Channel.CreateMessage(user, messageContent);
        }
        
        public System.IAsyncResult BeginCreateMessage(System.Guid user, string messageContent, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginCreateMessage(user, messageContent, callback, asyncState);
        }
        
        public M2LinkXamarin.WebServiceClients.MessageModel EndCreateMessage(System.IAsyncResult result)
        {
            return base.Channel.EndCreateMessage(result);
        }
    }
}
